// Datos de prueba para ver la app funcionando sin conectar Supabase todavía.
// En cuanto configures .env.local con tus llaves reales, la app deja de usar
// esto automáticamente y lee de la base de datos real.

export const MOCK_CASES = [
  {
    id: "1",
    pd: "Orange PD",
    report_number: "2025-MM-402193-A-O",
    suspect: "MARTINEZ, DEREK A.",
    incident_type: "Domestic Battery",
    status: "Closed",
    incident_date: "2025-03-11",
    charges: "Battery (Domestic) x1",
    rating: 4,
    report_link: "/sample-report.pdf",
    pdf_path: null,
  },
  {
    id: "2",
    pd: "Lee County",
    report_number: "25-MM-020417",
    suspect: "OKAFOR, JAMES B.",
    incident_type: "Fraud",
    status: "Closed",
    incident_date: "2025-01-22",
    charges: "Fraud / Scheme to Defraud",
    rating: 5,
    report_link: null,
    pdf_path: null,
  },
  {
    id: "3",
    pd: "St. Johns",
    report_number: "25000441MMMA",
    suspect: "REYNARD, KATHERINE M.",
    incident_type: "Child Neglect",
    status: "Ready to Review",
    incident_date: "2025-02-02",
    charges: "Neglect of a Child, Culpable Negligence",
    rating: 5,
    report_link: null,
    pdf_path: null,
  },
  {
    id: "4",
    pd: "Orange PD",
    report_number: "2025-MM-403981-A-A",
    suspect: "PETIDOR, JOHN R.",
    incident_type: "Homicide",
    status: "Closed",
    incident_date: "2025-04-17",
    charges: "Manslaughter, Resisting Officer",
    rating: 5,
    report_link: null,
    pdf_path: null,
  },
  {
    id: "5",
    pd: "Flagler SO",
    report_number: "2025 MM 000913",
    suspect: "COWART, ROBERT D.",
    incident_type: "DUI",
    status: "Closed",
    incident_date: "2025-11-05",
    charges: "DUI, Resisting Officer Without Violence",
    rating: 3,
    report_link: null,
    pdf_path: null,
  },
  {
    id: "6",
    pd: "St. Johns",
    report_number: "26000776MMMA",
    suspect: "THOMAS, YVONNE M.",
    incident_type: "Assault",
    status: "Ready to Review",
    incident_date: "2026-05-19",
    charges: "Assault on a Law Enforcement Officer",
    rating: 2,
    report_link: null,
    pdf_path: null,
  },
  {
    id: "7",
    pd: "Alachua SO",
    report_number: "25-AC-000112",
    suspect: "BRENNER, WILLA K.",
    incident_type: "Child Abuse",
    status: "Skipped",
    incident_date: "2025-06-30",
    charges: "Aggravated Child Abuse",
    rating: 5,
    report_link: null,
    pdf_path: null,
  },
  {
    id: "8",
    pd: "Lee County",
    report_number: "25-MM-000364",
    suspect: "ROSCITI, GENERO A.",
    incident_type: "Domestic Battery",
    status: "Graded",
    incident_date: "2025-06-03",
    charges: "Battery, Statutory Provision Violation",
    rating: 4,
    report_link: null,
    pdf_path: null,
  },
];
